### ISSUE TITLE
Squirrel for PC Engine

### ISSUE THREAD

**Issue by CGAWarlock** [pedipanol/mml-guide#34]
Not a real issue or anything, I just don't have Tumblr or Mastadon to message any other way.

There is also Squirrel for PC Engine.  It was written by Aetherbyte Studios well over 10 years ago now, based heavily off of the Develo MML/PSG information for PC Engine, in addition to borrowing some ideas from MusicA for MSX:

http://www.aetherbyte.com/aetherbyte-squirrel_for_pc-engine_and_turbografx-16.html

Definitely worth a mention.  We appreciate all you are doing for the advancement of MML for the masses, lol.

**Comment by pedipanol** [comment]
Added in the current guide update
